Repository code4romania/practice-for-good, pull requests merged in 2022-12, with the labels that each got.

#25 fix: [C4R-1189] missing word from card for number of hours
  src/assets/locales/ro/translation.json
  src/pages/programs/components/ProgramItem.tsx
Labels: bug :bug:, front-end

#28 fix: [C4R-1165] added max length to search field
  src/common/components/search-field/SearchField.tsx
Labels: bug :bug:, front-end

#26 fix: [C4R-1167] removed leading and trailing white spaces from search
  src/common/components/ngo-search/NGOSearch.tsx
  src/common/components/practice-programs-search/PracticeProgramsSearch.tsx
Labels: bug :bug:, front-end

#27 [C4R-1187] make direct call to cities query rather than through useCitiesQuery
  src/common/components/ngo-filter-modal/NGOFilterModal.tsx
  src/common/components/ngo-search/NGOSearch.tsx
  src/common/components/practice-program-filter-modal/PracticeProgramFilterModal.tsx
  src/common/components/practice-programs-search/PracticeProgramsSearch.tsx
  src/services/nomenclature/Nomeclature.queries.ts
Labels: bug :bug:

#31 fix: [C4R-1401] fixed error mesage on failing to load practice program
  src/common/components/shape-wrapper/ShapeWrapper.tsx
  src/pages/programs/Program.tsx
Labels: bug :bug:, front-end

#30 [Bugfix] Search form input fixes
  src/assets/locales/ro/translation.json
  src/common/components/date-picker/DatePicker.tsx
  src/common/components/header/Header.tsx
  src/common/components/ngo-filter-modal/NGOFilterModal.tsx
  src/common/components/ngo-search/NGOSearch.tsx
  src/common/components/practice-program-filter-modal/PracticeProgramFilterModal.tsx
  src/common/components/practice-programs-search/PracticeProgramsSearch.tsx
  src/common/components/search-field/SearchField.tsx
  src/common/components/select/Select.tsx
  src/common/components/server-select/ServerSelect.tsx
  src/common/components/sliding-menu/SlidingMenu.tsx
  src/common/helpers/Format.helper.ts
  src/index.css
  src/pages/organizations/components/OrganizationItem.tsx
  src/pages/programs/Program.tsx
  src/react-app-env.d.ts
Labels: bug :bug:

#29 fix: [C4R-1259] updated contact form field validations
  src/pages/contact/configs/Contact.config.ts
Labels: bug :bug:, front-end

#33 bugfix/C4R-1295
  src/common/components/card/Card.tsx
  src/index.css
  src/pages/organizations/components/OrganizationDetails.tsx
  src/pages/organizations/components/OrganizationItem.tsx
Labels: bug :bug:, front-end

#35 fix: [C4R-1259] wrong validation translations
  src/assets/locales/ro/translation.json
  src/pages/contact/configs/Contact.config.ts
Labels: bug :bug:, front-end

#37 C4R-1161 - Partial fixed counter trigger on scroll and changed animat…
  src/pages/landing/components/counter/CounterItem.tsx
Labels: bug :bug:, front-end

#34 C4R-1260 - Removed exclamation mark from inputs
  src/common/components/textarea/Textarea.tsx
Labels: bug :bug:, front-end

#38 fix: [C4R-1399] added reset filters button for mobile
  src/assets/locales/ro/translation.json
  src/common/components/ngo-filter-modal/NGOFilterModal.tsx
  src/common/components/practice-program-filter-modal/PracticeProgramFilterModal.tsx
  src/common/hooks/useToast.ts
  src/pages/contact/configs/Contact.config.ts
Labels: bug :bug:, front-end

#39 fix: [C4R-1209] changed contact data displayed when viewing one ong
  src/common/interfaces/Organization.interface.ts
  src/pages/organizations/components/OrganizationDetails.tsx
Labels: bug :bug:, front-end

#40 refactor: [C4R-1513] cleaned up translation file
  src/assets/locales/ro/translation.json
  src/common/components/ngo-search/NGOSearch.tsx
  src/common/components/ngo-search/configs/NGOSearch.config.ts
  src/common/components/practice-programs-search/PracticeProgramsSearch.tsx
  src/common/components/practice-programs-search/configs/PracticeProgramsSearch.config.ts
  src/common/components/select/Select.tsx
  src/pages/contact/Contact.tsx
  src/pages/landing/Landing.tsx
  src/pages/landing/components/domains/Domains.tsx
  src/pages/organizations/Organization.tsx
  src/pages/organizations/components/OrganizationDetails.tsx
  src/pages/programs/Program.tsx
Labels: content, front-end
