Repository code4romania/practice-for-good, pull requests merged in 2022-11, with the labels that each got.

#10 C4R-845: ONG Search
  src/assets/locales/ro/translation.json
  src/common/components/date-picker/DatePicker.tsx
  src/common/components/ngo-filter-modal/NGOFilterModal.tsx
  src/common/components/ngo-search/NGOSearch.tsx
  src/common/components/ngo-search/configs/NGOSearch.config.ts
  src/common/components/practice-program-filter-modal/PracticeProgramFilterModal.tsx
  src/common/components/practice-programs-search/PracticeProgramsSearch.tsx
  src/common/components/practice-programs-search/configs/PracticeProgramsSearch.config.ts
  src/common/components/select/Select.css
  src/common/components/select/Select.tsx
  src/common/components/server-select/ServerSelect.css
  src/common/interfaces/OrganizationFlat.interface.ts
  src/pages/organizations/Organizations.tsx
  src/services/organization/Organization.queries.ts
  src/services/organization/Organization.service.ts
  src/store/Selectors.ts
  src/store/Store.ts
  src/store/organizations/Organizations.selectors.ts
  src/store/organizations/Organizations.slice.ts
Labels: enhancement :rocket:, front-end

#12 C4R-851 Header + Footer
  src/assets/images/commit-global-logo-black.svg
  src/assets/images/commit-global-logo-white.svg
  src/assets/locales/ro/translation.json
  src/common/components/footer/Footer.tsx
  src/common/components/header/Header.tsx
  src/common/components/sliding-menu/SlidingMenu.tsx
  src/common/helpers/navigation.helper.ts
  src/index.css
  tailwind.config.js
Labels: enhancement :rocket:

#16 feat: [C4R-937] landing page counter FE
  package.json
  src/common/components/description/Description.tsx
  src/common/constants/CounterApp.constants.ts
  src/common/constants/nomenclature.constants.ts
  src/common/interfaces/LandingCounter.interface.ts
  src/pages/about/About.tsx
  src/pages/landing/Landing.tsx
  src/pages/landing/components/counter/Counter.tsx
  src/pages/landing/components/counter/CounterItem.tsx
  src/services/statistics/Statistics.queries.ts
  src/services/statistics/Statistics.services.ts
  src/store/Selectors.ts
Labels: enhancement :rocket:, front-end

#17 feat: [C4R-818] call API to send mail
  src/assets/locales/ro/translation.json
  src/common/interfaces/ContactMail.interface.ts
  src/pages/contact/Contact.tsx
  src/pages/contact/configs/Contact.config.ts
  src/services/public/PublicApi.queries.ts
  src/services/public/PublicApi.service.ts
Labels: enhancement :rocket:, front-end

#18 feat: [C4R-909] added app type to subject
  src/common/constants/MailAppType.constants.ts
  src/common/interfaces/ContactMail.interface.ts
  src/pages/contact/Contact.tsx
  src/pages/contact/configs/Contact.config.ts
Labels: enhancement :rocket:, front-end

#19 feat: [C4R-905] add breadcrumbs
  package-lock.json
  package.json
  src/common/components/breadcrumbs/Breadcrumbs.tsx
  src/common/components/sliding-menu/SlidingMenu.tsx
  src/common/constants/Menu.constants.ts
  src/common/containers/Layout.tsx
  src/common/router/Router.tsx
  src/services/organization/Organization.queries.ts
  src/services/practice-programs/PracticePrograms.queries.ts
  src/store/Store.ts
  src/store/organizations/Organizations.selectors.ts
  src/store/organizations/Organizations.slice.ts
  src/store/practice-programs/PracticePrograms.selectors.ts
  src/store/practice-programs/PracticePrograms.slice.ts
  tailwind.config.js
Labels: enhancement :rocket:

#20 C4R-987 - P4G Remaining UI items
  src/assets/images/background-search-image.png
  src/assets/locales/ro/translation.json
  src/common/components/date-picker/DatePicker.tsx
  src/common/components/footer/Footer.tsx
  src/common/components/header/Header.tsx
  src/common/components/ngo-filter-modal/NGOFilterModal.tsx
  src/common/components/ngo-search/NGOSearch.tsx
  src/common/components/ngo-search/configs/NGOSearch.config.ts
  src/common/components/practice-program-filter-modal/PracticeProgramFilterModal.tsx
  src/common/components/practice-programs-search/PracticeProgramsSearch.tsx
  src/common/components/practice-programs-search/configs/PracticeProgramsSearch.config.ts
  src/common/components/search-field/SearchField.tsx
  src/common/components/select/Select.css
  src/common/components/select/Select.tsx
  src/common/components/server-select/ServerSelect.css
  src/common/components/server-select/ServerSelect.tsx
  src/common/components/sliding-menu/SlidingMenu.tsx
  src/common/constants/ExternalURL.constants.ts
  src/pages/landing/Landing.tsx
  src/pages/landing/components/domains/Domain.tsx
  src/pages/organizations/Organizations.tsx
  src/pages/programs/Program.tsx
  src/pages/programs/Programs.tsx
  tailwind.config.js
Labels: enhancement :rocket:

#22 feat: [C4R-903] added search by domain from landing page
  src/common/constants/nomenclature.constants.ts
  src/pages/landing/Landing.tsx
  src/pages/landing/components/domains/Domain.tsx
  src/pages/landing/components/domains/Domains.tsx
Labels: enhancement :rocket:, front-end

#23 fix: [C4R-975] fix virtuoso -> virtuoso grid + ngo card adjustments
  src/common/components/card/Card.tsx
  src/index.css
  src/pages/organizations/Organizations.tsx
  src/pages/organizations/components/OrganizationItem.tsx
Labels: bug :bug:
